# Generated by Django 5.1.7 on 2025-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='store_faces/', verbose_name='Imagen')),
                ('encoding', models.JSONField(blank=True, null=True, verbose_name='Codificación Facial')),
            ],
        ),
    ]
